name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

permissions:
  contents: read
  checks: write

jobs:
  skip-check:
    runs-on: ubuntu-24.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@f75f66ce1886f00957d99748a42c724f4330bdcf # v5
        with:
          paths_ignore: '["**.md", "docs/**"]'
  build:
    runs-on: ubuntu-24.04
    needs: skip-check
    if: needs.skip-check.outputs.should_skip != 'true'
    steps:
      - name: system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libclang-dev llvm mold libncurses-dev build-essential fuse3 libfuse3-dev

      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - uses: dtolnay/rust-toolchain@888c2e1ea69ab0d4330cbf0af1ecc7b68f368cc1 # v1
        with:
          toolchain: 1.86
          components: clippy, rustfmt

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          persist-credentials: false

      - uses: Swatinem/rust-cache@9d47c6ad4b02e050fd481d890b2ea34778fd09d6 # v2

      - uses: taiki-e/install-action@86c23eed46c17b80677df6d8151545ce3e236c61 # v2
        with:
          tool: cargo-nextest

      - name: Build
        run: cargo build

      - name: Test
        run: cargo nextest run

      - name: SQLite Tests
        run: just run sqlite test

      - name: Fuse Tests
        run: |
          echo "user_allow_other" | sudo tee /etc/fuse.conf
          just run fuse test

      - name: Clippy
        uses: auguwu/clippy-action@94a9ff2f6920180b89e5c03d121d0af04a9d3e03 # 1.4.0
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Cargo fmt
        run: cargo fmt --check

      - name: Cargo doctests
        run: cargo test --doc
